### ISSUE TITLE
Site names including an underscore fail

### ISSUE THREAD

**Issue by timmyomahony** [timmyomahony/craft-remote-core#19]
For example, if your site is called `timmy_omahony` a new file will look like:

```
timmy_omahony__staging__221124_153839__kvpspomtqb__v4.3.3.sql 
```

The `_` in the name will cause the `RemoteFile` regex to crash. See here:

https://github.com/weareferal/craft-remote-core/blob/main/src/helpers/RemoteFile.php#L32

**Comment by ccchapman** [comment]
It seems there are other characters which `FileHelper::sanitizeFilename` does not remove (rightly so) but could be in your `Craft::$app->getSystemName()`.  For us, we had a right single quotation mark (`’`) in the system name which caused the `RemoteFile::__construct()` regular expression to fail.

**Comment by timmyomahony** [comment]
Hi @ccchapman, I've just pushed a new version of each plugin with a relaxed regex that should get rid of this issue. I'm going to close this, but if the problem remains please comment and I'll reopen.
